
-------------------------------- TICKET --------------------------------

CREATE TABLE TICKET(
    TICKET_NUM NUMBER NOT NULL,
    MT20ID VARCHAR2(200) NOT NULL,
    PRFNM VARCHAR2(200) NOT NULL,
    ID NUMBER NOT NULL,
    USER_ID VARCHAR2(200) NOT NULL,
    TICKET_QTY NUMBER NOT NULL,
    TICKET_TIME DATE DEFAULT SYSDATE NOT NULL,
    CHANGE_TIME DATE DEFAULT SYSDATE NOT NULL,
    PCSEGUIDANCE VARCHAR2(200) NOT NULL,
    TICKET_SEAT VARCHAR2(200) NOT NULL,
    TICKET_STATUS VARCHAR2(200) DEFAULT 'Y' NOT NULL
);

COMMENT ON COLUMN "TICKET"."TICKET_NUM" IS '예매번호';
COMMENT ON COLUMN "TICKET"."MT20ID" IS '공연ID';
COMMENT ON COLUMN "TICKET"."PRFNM" IS '공연명';
COMMENT ON COLUMN "TICKET"."ID" IS '회원번호';
COMMENT ON COLUMN "TICKET"."USER_ID" IS '아이디';
COMMENT ON COLUMN "TICKET"."TICKET_QTY" IS '인원';
COMMENT ON COLUMN "TICKET"."TICKET_TIME" IS '예매시작';
COMMENT ON COLUMN "TICKET"."CHANGE_TIME" IS '수정시각';
COMMENT ON COLUMN "TICKET"."PCSEGUIDANCE" IS '티켓가격';
COMMENT ON COLUMN "TICKET"."TICKET_SEAT" IS '좌석정보';
COMMENT ON COLUMN "TICKET"."TICKET_STATUS" IS '상태';

CREATE SEQUENCE SEQ_TICKET_NO;

COMMIT;

ROLLBACK;

INSERT INTO TICKET (
    TICKET_NUM, 
    MT20ID, 
   PRFNM, 
   ID, 
   USER_ID, 
   TICKET_QTY, 
   TICKET_TIME, 
   CHANGE_TIME, 
   PCSEGUIDANCE, 
   TICKET_SEAT, 
   TICKET_STATUS 
) VALUES(
    SEQ_TICKET_NO.NEXTVAL, 
    '202020DDD', 
    '공연제목010203', 
    20, 
    '유저아이디0102', 
    3, 
    DEFAULT, 
    DEFAULT, 
    '23000', 
    'A1, B2, C3', 
    DEFAULT           
);

-------------------------------------------------------------------------

-------------------------------- MEMBER --------------------------------

CREATE SEQUENCE MEM_SEQ; -- ID

CREATE TABLE MEMBER(
    ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(60) NOT NULL,
    USER_NICK VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(10) NOT NULL,
    USER_ROLE VARCHAR2(15) DEFAULT 'ROLE_USER', -- ROLE_USER / ROLE_ADMIN
    DATE_BIRTH DATE DEFAULT SYSDATE,
    GENDER VARCHAR2(10) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    POSTCODE VARCHAR2(15) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    DETAIL_ADDR VARCHAR2(100) NOT NULL,
    EXTRA_ADDR VARCHAR2(100) NOT NULL, -- 도로명주소를 지번주소로
    RANK VARCHAR2(20) DEFAULT '친구',
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
); 

-- TODO 구매이력, 회원등급

COMMIT;


SELECT * FROM MEMBER;

DROP TABLE MEMBER;

COMMENT ON COLUMN MEMBER.ID IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_NICK IS '닉네임';
COMMENT ON COLUMN MEMBER.USER_NAME IS '본명';
COMMENT ON COLUMN MEMBER.USER_ROLE IS '회원타입';
COMMENT ON COLUMN MEMBER.DATE_BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.POSTCODE IS '우편번호';
COMMENT ON COLUMN MEMBER.ADDRESS IS '도로명주소';
COMMENT ON COLUMN MEMBER.DETAIL_ADDR IS '상세주소';
COMMENT ON COLUMN MEMBER.EXTRA_ADDR IS '참고항목';
COMMENT ON COLUMN MEMBER.RANK IS '회원등급';
COMMENT ON COLUMN MEMBER.STATUS IS '탈퇴여부';

-------------------------------------------------------------------------

-------------------------------- BoxOffice 테이블 --------------------------------

CREATE TABLE BOXOFFICE (
    MT20ID VARCHAR2(100) PRIMARY KEY,
    AREA VARCHAR2(100),
    PRFDTCNT VARCHAR2(100),
    PRFPD VARCHAR2(100),
    CATE VARCHAR2(100),
    PRFPLCNM VARCHAR2(300),
    PRFNM VARCHAR2(300),
    RNUM VARCHAR2(100),
    SEATCNT VARCHAR2(100),
    POSTER VARCHAR2(300)
);

COMMENT ON COLUMN BOXOFFICE.MT20ID IS '공연ID';
COMMENT ON COLUMN BOXOFFICE.AREA IS '지역';
COMMENT ON COLUMN BOXOFFICE.PRFDTCNT IS '상연횟수';
COMMENT ON COLUMN BOXOFFICE.PRFPD IS '공연기간';
COMMENT ON COLUMN BOXOFFICE.CATE IS '장르';
COMMENT ON COLUMN BOXOFFICE.PRFPLCNM IS '공연장';
COMMENT ON COLUMN BOXOFFICE.PRFNM IS '공연명';
COMMENT ON COLUMN BOXOFFICE.RNUM IS '순위';
COMMENT ON COLUMN BOXOFFICE.SEATCNT IS '좌석수';
COMMENT ON COLUMN BOXOFFICE.POSTER IS '포스터';

-------------------------------------------------------------------------






















































